markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Andrew Goebel
blog_name: I don't know yet
url: agoebel.github.io
description: Jabber Jabber
twitter: 
github: agoebel